// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// FastComputeGCD
int FastComputeGCD(const int& num1, const int& num2);
RcppExport SEXP _Signac_FastComputeGCD(SEXP num1SEXP, SEXP num2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type num1(num1SEXP);
    Rcpp::traits::input_parameter< const int& >::type num2(num2SEXP);
    rcpp_result_gen = Rcpp::wrap(FastComputeGCD(num1, num2));
    return rcpp_result_gen;
END_RCPP
}
// FastComputeLCM
int FastComputeLCM(const int& num1, const int& num2);
RcppExport SEXP _Signac_FastComputeLCM(SEXP num1SEXP, SEXP num2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type num1(num1SEXP);
    Rcpp::traits::input_parameter< const int& >::type num2(num2SEXP);
    rcpp_result_gen = Rcpp::wrap(FastComputeLCM(num1, num2));
    return rcpp_result_gen;
END_RCPP
}
// FastGetCurrentDate
Rcpp::Date FastGetCurrentDate();
RcppExport SEXP _Signac_FastGetCurrentDate() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(FastGetCurrentDate());
    return rcpp_result_gen;
END_RCPP
}
// FastMatMult
arma::mat FastMatMult(const arma::mat& mat1, const arma::mat& mat2);
RcppExport SEXP _Signac_FastMatMult(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(FastMatMult(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}
// FastCreateSparseMat
arma::sp_mat FastCreateSparseMat(int nrow, int ncol);
RcppExport SEXP _Signac_FastCreateSparseMat(SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(FastCreateSparseMat(nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// FastStatsOfSparseMat
Rcpp::List FastStatsOfSparseMat(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastStatsOfSparseMat(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastStatsOfSparseMat(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastCreateFromTriplet
arma::sp_mat FastCreateFromTriplet(arma::urowvec vec1, arma::urowvec vec2, arma::colvec vec_val);
RcppExport SEXP _Signac_FastCreateFromTriplet(SEXP vec1SEXP, SEXP vec2SEXP, SEXP vec_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::urowvec >::type vec1(vec1SEXP);
    Rcpp::traits::input_parameter< arma::urowvec >::type vec2(vec2SEXP);
    Rcpp::traits::input_parameter< arma::colvec >::type vec_val(vec_valSEXP);
    rcpp_result_gen = Rcpp::wrap(FastCreateFromTriplet(vec1, vec2, vec_val));
    return rcpp_result_gen;
END_RCPP
}
// FastConvertToSparseMat
arma::sp_mat FastConvertToSparseMat(const SEXP& s);
RcppExport SEXP _Signac_FastConvertToSparseMat(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(FastConvertToSparseMat(s));
    return rcpp_result_gen;
END_RCPP
}
// FastConvertToTripletMat
Rcpp::List FastConvertToTripletMat(const SEXP& s);
RcppExport SEXP _Signac_FastConvertToTripletMat(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(FastConvertToTripletMat(s));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatSqrt
arma::sp_mat FastSparseMatSqrt(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastSparseMatSqrt(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatSqrt(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatMult
arma::sp_mat FastSparseMatMult(const arma::sp_mat& mat1, const arma::sp_mat& mat2);
RcppExport SEXP _Signac_FastSparseMatMult(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatMult(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatAddition
arma::sp_mat FastSparseMatAddition(const arma::sp_mat& mat1, const arma::sp_mat& mat2);
RcppExport SEXP _Signac_FastSparseMatAddition(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatAddition(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatMultWithNum
arma::sp_mat FastSparseMatMultWithNum(const arma::sp_mat& mat, const int& k);
RcppExport SEXP _Signac_FastSparseMatMultWithNum(SEXP matSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatMultWithNum(mat, k));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatSymmatl
arma::sp_mat FastSparseMatSymmatl(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastSparseMatSymmatl(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatSymmatl(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatTranspose
arma::sp_mat FastSparseMatTranspose(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastSparseMatTranspose(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatTranspose(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatTrimatu
arma::sp_mat FastSparseMatTrimatu(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastSparseMatTrimatu(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatTrimatu(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatTrace
int FastSparseMatTrace(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastSparseMatTrace(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatTrace(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastConvertToDiagonalSparseMat
arma::sp_mat FastConvertToDiagonalSparseMat(arma::sp_mat& mat);
RcppExport SEXP _Signac_FastConvertToDiagonalSparseMat(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastConvertToDiagonalSparseMat(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatSquare
arma::sp_mat FastSparseMatSquare(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastSparseMatSquare(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatSquare(mat));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatRepmat
arma::sp_mat FastSparseMatRepmat(const arma::sp_mat& mat, const int& i, const int& j);
RcppExport SEXP _Signac_FastSparseMatRepmat(SEXP matSEXP, SEXP iSEXP, SEXP jSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int& >::type i(iSEXP);
    Rcpp::traits::input_parameter< const int& >::type j(jSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatRepmat(mat, i, j));
    return rcpp_result_gen;
END_RCPP
}
// FastSparseMatSign
arma::sp_mat FastSparseMatSign(const arma::sp_mat& mat);
RcppExport SEXP _Signac_FastSparseMatSign(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(FastSparseMatSign(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Signac_FastComputeGCD", (DL_FUNC) &_Signac_FastComputeGCD, 2},
    {"_Signac_FastComputeLCM", (DL_FUNC) &_Signac_FastComputeLCM, 2},
    {"_Signac_FastGetCurrentDate", (DL_FUNC) &_Signac_FastGetCurrentDate, 0},
    {"_Signac_FastMatMult", (DL_FUNC) &_Signac_FastMatMult, 2},
    {"_Signac_FastCreateSparseMat", (DL_FUNC) &_Signac_FastCreateSparseMat, 2},
    {"_Signac_FastStatsOfSparseMat", (DL_FUNC) &_Signac_FastStatsOfSparseMat, 1},
    {"_Signac_FastCreateFromTriplet", (DL_FUNC) &_Signac_FastCreateFromTriplet, 3},
    {"_Signac_FastConvertToSparseMat", (DL_FUNC) &_Signac_FastConvertToSparseMat, 1},
    {"_Signac_FastConvertToTripletMat", (DL_FUNC) &_Signac_FastConvertToTripletMat, 1},
    {"_Signac_FastSparseMatSqrt", (DL_FUNC) &_Signac_FastSparseMatSqrt, 1},
    {"_Signac_FastSparseMatMult", (DL_FUNC) &_Signac_FastSparseMatMult, 2},
    {"_Signac_FastSparseMatAddition", (DL_FUNC) &_Signac_FastSparseMatAddition, 2},
    {"_Signac_FastSparseMatMultWithNum", (DL_FUNC) &_Signac_FastSparseMatMultWithNum, 2},
    {"_Signac_FastSparseMatSymmatl", (DL_FUNC) &_Signac_FastSparseMatSymmatl, 1},
    {"_Signac_FastSparseMatTranspose", (DL_FUNC) &_Signac_FastSparseMatTranspose, 1},
    {"_Signac_FastSparseMatTrimatu", (DL_FUNC) &_Signac_FastSparseMatTrimatu, 1},
    {"_Signac_FastSparseMatTrace", (DL_FUNC) &_Signac_FastSparseMatTrace, 1},
    {"_Signac_FastConvertToDiagonalSparseMat", (DL_FUNC) &_Signac_FastConvertToDiagonalSparseMat, 1},
    {"_Signac_FastSparseMatSquare", (DL_FUNC) &_Signac_FastSparseMatSquare, 1},
    {"_Signac_FastSparseMatRepmat", (DL_FUNC) &_Signac_FastSparseMatRepmat, 3},
    {"_Signac_FastSparseMatSign", (DL_FUNC) &_Signac_FastSparseMatSign, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_Signac(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
