# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastComputeGCD <- function(num1, num2) {
    .Call(`_Signac_FastComputeGCD`, num1, num2)
}

FastComputeLCM <- function(num1, num2) {
    .Call(`_Signac_FastComputeLCM`, num1, num2)
}

FastGetCurrentDate <- function() {
    .Call(`_Signac_FastGetCurrentDate`)
}

FastMatMult <- function(mat1, mat2) {
    .Call(`_Signac_FastMatMult`, mat1, mat2)
}

FastCreateSparseMat <- function(nrow, ncol) {
    .Call(`_Signac_FastCreateSparseMat`, nrow, ncol)
}

FastStatsOfSparseMat <- function(mat) {
    .Call(`_Signac_FastStatsOfSparseMat`, mat)
}

FastCreateFromTriplet <- function(vec1, vec2, vec_val) {
    .Call(`_Signac_FastCreateFromTriplet`, vec1, vec2, vec_val)
}

FastConvertToSparseMat <- function(s) {
    .Call(`_Signac_FastConvertToSparseMat`, s)
}

FastConvertToTripletMat <- function(s) {
    .Call(`_Signac_FastConvertToTripletMat`, s)
}

FastSparseMatSqrt <- function(mat) {
    .Call(`_Signac_FastSparseMatSqrt`, mat)
}

FastSparseMatMult <- function(mat1, mat2) {
    .Call(`_Signac_FastSparseMatMult`, mat1, mat2)
}

FastSparseMatAddition <- function(mat1, mat2) {
    .Call(`_Signac_FastSparseMatAddition`, mat1, mat2)
}

FastSparseMatMultWithNum <- function(mat, k) {
    .Call(`_Signac_FastSparseMatMultWithNum`, mat, k)
}

FastSparseMatSymmatl <- function(mat) {
    .Call(`_Signac_FastSparseMatSymmatl`, mat)
}

FastSparseMatTranspose <- function(mat) {
    .Call(`_Signac_FastSparseMatTranspose`, mat)
}

FastSparseMatTrimatu <- function(mat) {
    .Call(`_Signac_FastSparseMatTrimatu`, mat)
}

FastSparseMatTrace <- function(mat) {
    .Call(`_Signac_FastSparseMatTrace`, mat)
}

FastConvertToDiagonalSparseMat <- function(mat) {
    .Call(`_Signac_FastConvertToDiagonalSparseMat`, mat)
}

FastSparseMatSquare <- function(mat) {
    .Call(`_Signac_FastSparseMatSquare`, mat)
}

FastSparseMatRepmat <- function(mat, i, j) {
    .Call(`_Signac_FastSparseMatRepmat`, mat, i, j)
}

FastSparseMatSign <- function(mat) {
    .Call(`_Signac_FastSparseMatSign`, mat)
}

