# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastComputeGCD <- function(num1, num2) {
    .Call(`_Signac_FastComputeGCD`, num1, num2)
}

FastComputeLCM <- function(num1, num2) {
    .Call(`_Signac_FastComputeLCM`, num1, num2)
}

FastGetCurrentDate <- function() {
    .Call(`_Signac_FastGetCurrentDate`)
}

FastDiffVector <- function(a, b) {
    .Call(`_Signac_FastDiffVector`, a, b)
}

FastRandVector <- function(num) {
    .Call(`_Signac_FastRandVector`, num)
}

FastMatMult <- function(mat1, mat2) {
    .Call(`_Signac_FastMatMult`, mat1, mat2)
}

FastGetRowsOfMat <- function(mat, vec) {
    .Call(`_Signac_FastGetRowsOfMat`, mat, vec)
}

FastGetColsOfMat <- function(mat, vec) {
    .Call(`_Signac_FastGetColsOfMat`, mat, vec)
}

FastGetSubMat <- function(mat, rvec, cvec) {
    .Call(`_Signac_FastGetSubMat`, mat, rvec, cvec)
}

FastCreateSparseMat <- function(nrow, ncol) {
    .Call(`_Signac_FastCreateSparseMat`, nrow, ncol)
}

FastStatsOfSparseMat <- function(mat) {
    .Call(`_Signac_FastStatsOfSparseMat`, mat)
}

FastCreateFromTriplet <- function(vec1, vec2, vec_val) {
    .Call(`_Signac_FastCreateFromTriplet`, vec1, vec2, vec_val)
}

FastConvertToSparseMat <- function(s) {
    .Call(`_Signac_FastConvertToSparseMat`, s)
}

FastConvertToTripletMat <- function(s) {
    .Call(`_Signac_FastConvertToTripletMat`, s)
}

FastSparseMatSqrt <- function(mat) {
    .Call(`_Signac_FastSparseMatSqrt`, mat)
}

FastSparseMatMult <- function(mat1, mat2) {
    .Call(`_Signac_FastSparseMatMult`, mat1, mat2)
}

FastSparseMatAddition <- function(mat1, mat2) {
    .Call(`_Signac_FastSparseMatAddition`, mat1, mat2)
}

FastSparseMatMultWithNum <- function(mat, k) {
    .Call(`_Signac_FastSparseMatMultWithNum`, mat, k)
}

FastSparseMatSymmatl <- function(mat) {
    .Call(`_Signac_FastSparseMatSymmatl`, mat)
}

FastSparseMatTranspose <- function(mat) {
    .Call(`_Signac_FastSparseMatTranspose`, mat)
}

FastSparseMatTrimatu <- function(mat) {
    .Call(`_Signac_FastSparseMatTrimatu`, mat)
}

FastSparseMatTrace <- function(mat) {
    .Call(`_Signac_FastSparseMatTrace`, mat)
}

FastConvertToDiagonalSparseMat <- function(mat) {
    .Call(`_Signac_FastConvertToDiagonalSparseMat`, mat)
}

FastSparseMatSquare <- function(mat) {
    .Call(`_Signac_FastSparseMatSquare`, mat)
}

FastSparseMatRepmat <- function(mat, i, j) {
    .Call(`_Signac_FastSparseMatRepmat`, mat, i, j)
}

FastSparseMatSign <- function(mat) {
    .Call(`_Signac_FastSparseMatSign`, mat)
}

FastSparseMatMultSD <- function(mat1, mat2) {
    .Call(`_Signac_FastSparseMatMultSD`, mat1, mat2)
}

FastSparseMatMultDS <- function(mat1, mat2) {
    .Call(`_Signac_FastSparseMatMultDS`, mat1, mat2)
}

FastSparseMatMultDD <- function(mat1, mat2) {
    .Call(`_Signac_FastSparseMatMultDD`, mat1, mat2)
}

FastGetRowOfSparseMat <- function(mat, i) {
    .Call(`_Signac_FastGetRowOfSparseMat`, mat, i)
}

FastGetColOfSparseMat <- function(mat, j) {
    .Call(`_Signac_FastGetColOfSparseMat`, mat, j)
}

FastGetRowsOfSparseMat <- function(mat, start, end) {
    .Call(`_Signac_FastGetRowsOfSparseMat`, mat, start, end)
}

FastGetColsOfSparseMat <- function(mat, start, end) {
    .Call(`_Signac_FastGetColsOfSparseMat`, mat, start, end)
}

FastGetSubSparseMat <- function(mat, rrvec, ccvec) {
    .Call(`_Signac_FastGetSubSparseMat`, mat, rrvec, ccvec)
}

FastGetSubSparseMatByRows <- function(mat, rvec) {
    .Call(`_Signac_FastGetSubSparseMatByRows`, mat, rvec)
}

FastGetSubSparseMatByCols <- function(mat, cvec) {
    .Call(`_Signac_FastGetSubSparseMatByCols`, mat, cvec)
}

FastGetSumSparseMatByRows <- function(mat, rvec) {
    .Call(`_Signac_FastGetSumSparseMatByRows`, mat, rvec)
}

FastGetSumSparseMatByCols <- function(mat, cvec) {
    .Call(`_Signac_FastGetSumSparseMatByCols`, mat, cvec)
}

FastGetSumSparseMatByAllRows <- function(mat) {
    .Call(`_Signac_FastGetSumSparseMatByAllRows`, mat)
}

FastGetSumSparseMatByAllRowsV2 <- function(mat) {
    .Call(`_Signac_FastGetSumSparseMatByAllRowsV2`, mat)
}

FastGetSumSparseMatByAllCols <- function(mat) {
    .Call(`_Signac_FastGetSumSparseMatByAllCols`, mat)
}

